### ISSUE TITLE
where can we download learned models?

### ISSUE THREAD

**Issue by CoolDarran** [Hironsan/anago#3]
hi @Hironsan 

As Feature Support said:
> downloading learned model for many tasks. (e.g. NER, POS Tagging, etc...)

but I can not find how to download learned model

**Comment by Hironsan** [comment]
Hi, @CoolDarran . Thank you for the question.

I apologize for the confusion.

I defined [download function](https://github.com/Hironsan/anago/blob/master/anago/data/utils.py), but as for now, downloading learned model has not been supported because of some technical problems.

I will fix the README.md and I will do the best to solve the problems.
